FROM node:14-alpine

VOLUME /web

RUN yarn remove node-sass
RUN yarn add node-sass@4.14.1

# CMD [ "yarn", "remove", "node-sass" ]
# CMD [ "yarn", "add", "node-sass@4.14.1" ]

CMD [ "yarn", "start" ]
