FROM node:14-alpine

WORKDIR /web
COPY . /web

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python
RUN yarn
RUN yarn add serve node-gyp
RUN yarn build
# RUN npx serve -s build

# TODO build
# CMD [ "yarn", "build" ]
# CMD [ "yarn", "add", "serve" ]

CMD [ "npx", "serve", "-s", "build" ]
